(()=>{
    const $=id=>document.getElementById(id);const stops=['Retiro','Saldías','Ciudad Universitaria','Aristóbulo del Valle','M. M. Padilla','Florida','Munro','Carapachay','Villa Adelina','Boulogne Sur Mer','Vice Alte. Montes','Don Torcuato','A. Sourdeaux','Villa de Mayo','Los Polvorines','Ing. Pablo Nogués','Grand Bourg','Tierras Altas','Tortuguitas','Manuel Alberti','Del Viso','Villa Rosa'].map((name,index)=>({id:index,name,aliases:name==='Aristóbulo del Valle'?['A. Del Valle']:[]}));let selected=null,direction='Villa Rosa';
    const title=$('station-title'),results=$('results'),status=$('feed-status'),input=$('station-search');
    function setStatus(message,live=false){status.innerHTML='<span class="statusdot '+(live?'live':'')+'"></span><span>'+message+'</span>'}
    function norm(text){return text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
    function findStations(q){return stops.filter(s=>[s.name,...s.aliases].some(name=>norm(name).includes(norm(q)))).slice(0,8)}
    function pickStation(s){selected=s;input.value=s.name;render()}
    function search(){const q=input.value.trim();if(!q)return;const matches=findStations(q);if(matches.length===1){pickStation(matches[0]);return}if(!matches.length){results.innerHTML='<div class="empty"><strong>No encontramos esa estación</strong>Busca una de las 22 paradas del Belgrano Norte.</div>';return}results.innerHTML='<div class="empty"><strong>Elige una estación</strong><div class="recent" style="justify-content:center;margin-top:14px">'+matches.map((s,i)=>'<button class="chip" data-result="'+i+'">'+escapeHtml(s.name)+'</button>').join('')+'</div></div>';results.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>pickStation(matches[Number(b.dataset.result)])))}
    function escapeHtml(t){return String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function render(){if(!selected)return;title.textContent=selected.name;setStatus('Servicio '+selected.name+' → '+direction);const link='https://proximostrenes.ferrovias.com.ar/';const schedule='https://www.ferrovias.com.ar/imgs/MuralH21.pdf';results.innerHTML='<div class="empty"><strong>Desde '+escapeHtml(selected.name)+' hacia '+escapeHtml(direction)+'</strong>Abre el tablero oficial para consultar los próximos trenes y el horario publicado por Ferrovías.<div class="recent" style="justify-content:center;margin-top:18px"><a class="find" style="display:inline-flex;align-items:center;justify-content:center;text-decoration:none;padding:0 16px;width:auto" href="'+link+'" target="_blank" rel="noreferrer">Ver próximos trenes ↗</a><a class="refresh" style="display:inline-flex;align-items:center;text-decoration:none" href="'+schedule+'" target="_blank" rel="noreferrer">Horario del ramal ↗</a></div></div>'}
    document.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>{direction=b.dataset.direction;document.querySelectorAll('[data-direction]').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));x.classList.toggle('selected-direction',x===b)});render()}));
    $('search-button').addEventListener('click',search);input.addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.query;search()}));
    if(document.modelContext?.registerTool){const controller=new AbortController();try{document.modelContext.registerTool({name:'select_belgrano_norte_station',title:'Elegir estación del Belgrano Norte',description:'Selecciona una de las estaciones entre Retiro y Villa Rosa y consulta los enlaces oficiales de arribos y horarios.',inputSchema:{type:'object',properties:{station:{type:'string',description:'Nombre de una estación del Belgrano Norte'}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute({station}){input.value=String(station||'');search();return {station:title.textContent,direction,details:results.innerText.slice(0,1200)}}},{signal:controller.signal})}catch(e){}}
  })();
